name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      env: 
        RAW_REPO_NAME: ${{ github.repository }}
      run: |
        #make lowercase
        IMAGE_NAME=${RAW_REPO_NAME,,}      
        docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)
        docker image ls

